// Bundles the CLI into action/cli.mjs so the GitHub Action runs reviewed, committed JavaScript
// without installing dependencies or compiling TypeScript at runtime (RFC 0014 §10).
//   node scripts/build-action.mjs          write action/cli.mjs
//   node scripts/build-action.mjs --check  fail when the committed bundle differs from the source
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import console from "node:console";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outfile = path.join(root, "action", "cli.mjs");
const { version } = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));

// version.ts searches parent directories for a package.json, which is unreliable inside the
// Action's install location. The bundle pins the version it was built from instead.
const pinVersion = {
  name: "pin-package-version",
  setup(builder) {
    builder.onLoad({ filter: /[\\/]src[\\/]cli[\\/]version\.ts$/ }, () => ({
      contents: `export function packageVersion(): string { return ${JSON.stringify(version)}; }\n`,
      loader: "ts",
    }));
  },
};

const result = await build({
  entryPoints: [path.join(root, "src", "cli.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  write: false,
  legalComments: "eof",
  // CommonJS dependencies (ajv, commander) need `require` inside an ES module bundle.
  // Generated output: linting covers the source, not this bundle.
  banner: { js: "/* eslint-disable */\n// Generated by scripts/build-action.mjs from src/; do not edit.\nimport { createRequire as __engineeringspecCreateRequire } from \"node:module\";\nconst require = __engineeringspecCreateRequire(import.meta.url);" },
  logLevel: "silent",
  plugins: [pinVersion],
});
const bundle = result.outputFiles[0].text;

if (process.argv.includes("--check")) {
  let committed = "";
  try {
    committed = await readFile(outfile, "utf8");
  } catch {
    committed = "";
  }
  if (committed !== bundle) {
    console.error("action/cli.mjs does not match the current source. Run `npm run build:action` and commit the result.");
    process.exit(1);
  }
  console.log("action/cli.mjs matches the current source.");
} else {
  await writeFile(outfile, bundle);
  console.log(`wrote ${path.relative(root, outfile)} (${Math.round(bundle.length / 1024)} KiB)`);
}
